### ISSUE TITLE
Remove some Launch settings

### ISSUE THREAD

**Issue by FlorianTolk** [adlnet/cmi5-player-moodle-plugin#14]
**Is your feature request related to a problem? Please describe.**
Moodle currently displays 2 "launch settings" that should be set by the cmi5 player.
![image](https://github.com/adlnet/cmi5-player-moodle-plugin/assets/33456535/11a9c252-d50f-4087-a036-fceec5cb2bfa)

**Describe the solution you'd like**
Remove these 2 options from the UI, and change the name of this section to "cmi5 package upload"

**Comment by ADLMeganBohland** [comment]
I have made this update, however due to code freeze on our server for testing, I cannot currently upload. However, here are the changes:
![image](https://github.com/adlnet/cmi5-player-moodle-plugin/assets/99821412/f4993959-4881-492f-bb76-692dcdc91276)

If this is what you have in mind we can close this out

**Comment by ADLMeganBohland** [comment]
Code freeze was lifted and changes applied
